/**
 * /b/[slug]?t=<accessToken> — Public event-signup landing.
 *
 * This is the URL embedded in the QR generated by /api/event/qr. Before this
 * page existed, clicking a QR link returned 404 which silently broke the
 * whole public-link signup flow. The page validates the token server-side,
 * displays event metadata, and renders the applicant form; submission goes
 * through the existing POST /api/event/submit.
 */
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { tokensEqual } from "@/lib/event/tokens";
import { parseCustomQuestions } from "@/lib/event/schemas";
import { EventSignupForm } from "@/components/event/EventSignupForm";

type SearchParams = Promise<{ t?: string }>;

export default async function PublicEventSignupPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string }>;
  searchParams: SearchParams;
}) {
  const { slug } = await params;
  const { t } = await searchParams;

  const board = await db.board.findFirst({
    where: { OR: [{ slug }, { id: slug }] },
  });
  if (!board) notFound();
  if (board.layout !== "event-signup") {
    return (
      <main className="board-page">
        <div className="forbidden-card">
          <h2>잘못된 보드 유형</h2>
          <p>이 링크는 행사 신청 보드 전용이에요.</p>
        </div>
      </main>
    );
  }
  if (board.accessMode !== "public-link" || !board.accessToken) {
    return (
      <main className="board-page">
        <div className="forbidden-card">
          <h2>공개 링크가 비활성화됐어요</h2>
          <p>교사에게 다시 링크를 요청해 주세요.</p>
        </div>
      </main>
    );
  }
  if (!t || !tokensEqual(t, board.accessToken)) {
    return (
      <main className="board-page">
        <div className="forbidden-card">
          <h2>만료된 링크예요</h2>
          <p>
            QR/링크가 갱신되었어요. 교사에게 최신 공개 링크를 다시 받아 주세요.
          </p>
        </div>
      </main>
    );
  }

  const now = new Date();
  const notOpenYet = board.applicationStart && now < board.applicationStart;
  const closed = board.applicationEnd && now > board.applicationEnd;

  const questions = parseCustomQuestions(board.customQuestions);

  return (
    <main className="board-page event-public-page">
      <article className="event-public-card">
        {board.eventPosterUrl && (
          // Public page — student may be on any device/network, so we skip
          // next/image optimization to avoid a cold loader round-trip.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={board.eventPosterUrl}
            alt="행사 포스터"
            className="event-public-poster"
          />
        )}
        <h1 className="event-public-title">{board.title}</h1>
        {board.description && (
          <p className="event-public-desc">{board.description}</p>
        )}
        <dl className="event-public-meta">
          {board.venue && (
            <>
              <dt>장소</dt>
              <dd>{board.venue}</dd>
            </>
          )}
          {board.eventStart && (
            <>
              <dt>일시</dt>
              <dd>
                {new Date(board.eventStart).toLocaleString("ko-KR", {
                  timeZone: "Asia/Seoul",
                })}
                {board.eventEnd
                  ? ` ~ ${new Date(board.eventEnd).toLocaleString("ko-KR", {
                      timeZone: "Asia/Seoul",
                    })}`
                  : ""}
              </dd>
            </>
          )}
          {board.applicationEnd && (
            <>
              <dt>신청 마감</dt>
              <dd>
                {new Date(board.applicationEnd).toLocaleString("ko-KR", {
                  timeZone: "Asia/Seoul",
                })}
              </dd>
            </>
          )}
        </dl>

        {notOpenYet ? (
          <div className="event-public-notice">
            아직 신청이 시작되지 않았어요. 시간 맞춰 다시 방문해 주세요.
          </div>
        ) : closed ? (
          <div className="event-public-notice">
            신청이 마감됐어요.
          </div>
        ) : (
          <EventSignupForm
            boardId={board.id}
            token={t}
            ask={{
              name: board.askName,
              gradeClass: board.askGradeClass,
              studentNumber: board.askStudentNumber,
              contact: board.askContact,
            }}
            allowTeam={board.allowTeam}
            maxTeamSize={board.maxTeamSize}
            videoPolicy={board.videoPolicy}
            videoProviders={board.videoProviders}
            customQuestions={questions}
            requireApproval={board.requireApproval}
          />
        )}
      </article>
    </main>
  );
}
